// <auto-generated />
namespace CadeMeuPet.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _init_26052019 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_init_26052019));
        
        string IMigrationMetadata.Id
        {
            get { return "201905261212406__init_26052019"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
