// <auto-generated />
namespace CadeMeuPet.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class alter_animal_18072019 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alter_animal_18072019));
        
        string IMigrationMetadata.Id
        {
            get { return "201907190055401_alter_animal_18072019"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
