// <auto-generated />
namespace CadeMeuPet.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class alter_tab_animal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alter_tab_animal));
        
        string IMigrationMetadata.Id
        {
            get { return "201909082256506_alter_tab_animal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
